import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav
          style={{
            width: "100%",
            background: "teal",
            fontSize: "30px",
            display: "flex",
            justifyContent: "space-between",
          }}
        >
          <Link href="/">home page </Link>
          <Link href="articles">Articles</Link>
          <Link href="posts">posts</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
